// src/lib/richtext-renderer/svelte/RichTextMark.svelte
<script lang="ts">
  import type { PMMark, StoryblokRichTextComponentMap } from "../";
  import { resolveComponent, resolveMarkTag, transformAttrs } from "../";

  export let mark: PMMark;
  export let components: StoryblokRichTextComponentMap | undefined;

  const MarkComponent = resolveComponent(mark.type, components);
  const Tag = !MarkComponent ? resolveMarkTag(mark) : null;

  const attrs = !MarkComponent
    ? transformAttrs(mark.attrs, { markType: mark.type })
    : {};
</script>

{#if MarkComponent}
  <svelte:component this={MarkComponent} {...mark} {components}>
    <slot />
  </svelte:component>

{:else if Tag}
  {#if typeof Tag === "string"}
    <svelte:element this={Tag} {...attrs}>
      <slot />
    </svelte:element>
  {:else}
    <svelte:component this={Tag} {...attrs}>
      <slot />
    </svelte:component>
  {/if}

{/if}

// src/lib/richtext-renderer/vue/RichTextMark.vue
<script setup lang="ts">
import { computed, h, type VNode } from "vue";
import type { PMNode, StoryblokRichTextComponentMap } from "..";
import {
  resolveMarkTag,
  styleStringToObject,
  transformAttrs,
} from "../../utils";

interface RichTextMarkProps {
  node: PMNode;
  components?: StoryblokRichTextComponentMap;
}

const props = defineProps<RichTextMarkProps>();

const renderMarks = (): string | VNode => {
  const marks = props.node.marks ?? [];
  let element: string | VNode = props.node.text ?? "";

  for (let i = marks.length - 1; i >= 0; i--) {
    const mark = marks[i];
    const Tag = resolveMarkTag(mark);
    const { style, ...rest } = transformAttrs(mark.attrs, {
      markType: mark.type,
    });
    element = h(Tag, { ...rest, style: styleStringToObject(style) }, element);
  }

  return element;
};

const finalRender = computed(() => renderMarks());
</script>

<template>
  <component :is="finalRender" />
</template>
