// src/lib/richtext-renderer/react/RichTextMark.tsx
import React, { type JSX } from "react";
import type { PMMark, PMNode, StoryblokRichTextComponentMap } from "..";
import { resolveMarkTag, styleStringToObject, transformAttrs } from "../utils";

interface RichTextMarkProps {
  node: Extract<PMNode, { type: "text" }>;
  components?: StoryblokRichTextComponentMap;
}

const RichTextMark: React.FC<RichTextMarkProps> = ({ node, components }) => {
  const marks = node?.marks ?? [];

  function GetComponent(mark: PMMark) {
  return components?.[mark.type] as React.ComponentType<any> | undefined;
  }

  let content: any = node?.text ?? "";
  // Wrap marks inside-out
  for (let i = 0; i < marks.length; i++) {
    const mark = marks[i];
    const CustomComponent = GetComponent(mark);
    if (CustomComponent) {
      content = (
        <CustomComponent {...mark} components={components}>{content}</CustomComponent>
      );
      continue;
    }
    const Tag = resolveMarkTag(mark) as keyof JSX.IntrinsicElements;

    const {style,...rest} = transformAttrs(mark.attrs, { markType: mark.type });

    content = React.createElement(Tag, { ...rest, style: styleStringToObject(style) }, content);
  }
  return <>{content}</>;
};

export default RichTextMark;

// src/lib/richtext-renderer/vue/RichTextMark.vue
<script setup lang="ts">
import { computed, h, type VNode } from "vue";
import type { PMNode, StoryblokRichTextComponentMap } from "..";
import {
  resolveMarkTag,
  styleStringToObject,
  transformAttrs,
} from "../../utils";

interface RichTextMarkProps {
  node: PMNode;
  components?: StoryblokRichTextComponentMap;
}

const props = defineProps<RichTextMarkProps>();

const renderMarks = (): string | VNode => {
  const marks = props.node.marks ?? [];
  let element: string | VNode = props.node.text ?? "";

  for (let i = marks.length - 1; i >= 0; i--) {
    const mark = marks[i];
    const Tag = resolveMarkTag(mark);
    const { style, ...rest } = transformAttrs(mark.attrs, {
      markType: mark.type,
    });
    element = h(Tag, { ...rest, style: styleStringToObject(style) }, element);
  }

  return element;
};

const finalRender = computed(() => renderMarks());
</script>

<template>
  <component :is="finalRender" />
</template>
